### ISSUE TITLE
Can't create payment in your Web demo

### ISSUE THREAD

**Issue by maurictg** [Viincenttt/MollieApi#134]
Dear Vincent,
I've an error thats called in Dutch _hardnekkig_:
**MollieApiException: Unprocessable Entity - The amount contains an invalid value**

_The data I've posted:_
Amount: 10.00 (also tried 10,00 and other values)
Currentcy: EUR
Description: test

I can't figure out why this error occured. Can you explain how to fix it?
Note: I am using a test key with a new made mollie account.
The full error:

Mollie.Api.Client.MollieApiException: Unprocessable Entity - The amount contains an invalid value

   at Mollie.Api.Client.BaseMollieClient.ProcessHttpResponseMessage[T](HttpResponseMessage response) in C:\Users\maurict\Documents\GitHub\MollieApi\Mollie.Api\Client\BaseMollieClient.cs:line 86

   at Mollie.Api.Client.BaseMollieClient.SendHttpRequest[T](HttpMethod httpMethod, String relativeUri, Object data) in C:\Users\maurict\Documents\GitHub\MollieApi\Mollie.Api\Client\BaseMollieClient.cs:line 39

   at Mollie.Api.Client.BaseMollieClient.PostAsync[T](String relativeUri, Object data) in C:\Users\maurict\Documents\GitHub\MollieApi\Mollie.Api\Client\BaseMollieClient.cs:line 57

   at Mollie.Api.Client.PaymentClient.CreatePaymentAsync(PaymentRequest paymentRequest) in C:\Users\maurict\Documents\GitHub\MollieApi\Mollie.Api\Client\PaymentClient.cs:line 22

   at Mollie.WebApplicationCoreExample.Services.Payment.PaymentStorageClient.Create(CreatePaymentModel model) in C:\Users\maurict\Documents\GitHub\MollieApi\Mollie.WebApplicationCoreExample\Services\Payment\PaymentStorageClient.cs:line 24

   at Mollie.WebApplicationCoreExample.Controllers.PaymentController.Create(CreatePaymentModel model) in C:\Users\maurict\Documents\GitHub\MollieApi\Mollie.WebApplicationCoreExample\Controllers\PaymentController.cs:line 48

   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at System.Threading.Tasks.ValueTask`1.get_Result()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()

   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by maurictg** [comment]
(I've cloned your WebApplicationCoreExample), only changed the mollie token and dropping into this error

**Comment by mpiri** [comment]
hi,
I also have this error. I comment line 9 on the model "createpaymentmodel.cs' to be able to test further.

// [RegularExpression(@"\d+(\.\d{2})?", ErrorMessage = "Please enter an amount with two decimal places")]

I've also tried another expression but without succes.

regards

**Comment by kryptonite** [comment]
I think both of you are running into a localization issue. The regex does not allow for "," to be used in the amount. It requires the use of "." or no decimal separator. But when you try "10.00" and get the "The amount contains an invalid value" error, you are probably running this on a thread with "nl-NL" culture settings. This causes the "10.00" you post to be mapped to a decimal of 1000. Mollie will not accept this because it requires two decimal places.

I suggest you run your thread on "en-US" culture and use a "." as decimal separator. Or if you need to run the thread under "nl-NL" remove the regex from the CreatePaymentModel and then use a "," as separator.

**Comment by Viincenttt** [comment]
What kryptonite says is 100% correct. If anyone wants to put some effort into this, feel free to create a pull request for a solution that is not dependent on the culture settings of the server/development environment.

**Comment by maurictg** [comment]
Thank you all, for now this error can be fixed with commenting the regex pattern in CreatePaymentModel.cs like kryptonite said. 
So I'll close this issue.

(But now i'm jumping into an "No suitable payment methods found" issue, but i'll worry about that later.)
