### ISSUE TITLE
kbc pay type is not supported

### ISSUE THREAD

**Issue by abereznyi** [Viincenttt/MollieApi#21]
Mollie added a new payment type "KBC/CBC Payment Button", which is not supported as yet - please add it.

Current API 1.3.6 throws error when KBC/CBC Payment Button is used:

System.ArgumentException: Requested value 'kbc' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Mollie.Api.JsonConverters.PaymentResponseConverter.GetPaymentMethod(JObject jObject) in E:\Development\GitHub\MollieApi\Mollie.Api\JsonConverters\PaymentResponseConverter.cs:line 26
   at Mollie.Api.JsonConverters.PaymentResponseConverter.Create(Type objectType, JObject jObject) in E:\Development\GitHub\MollieApi\Mollie.Api\JsonConverters\PaymentResponseConverter.cs:line 17
   at Mollie.Api.JsonConverters.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in E:\Development\GitHub\MollieApi\Mollie.Api\JsonConverters\JsonCreationConverter.cs:line 39
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Mollie.Api.Client.MollieClient.ProcessHttpResponseMessage[T](IRestResponse response) in E:\Development\GitHub\MollieApi\Mollie.Api\Client\MollieClient.cs:line 173

**Comment by Viincenttt** [comment]
Fixed in 58d586ec27c773957e2f313217b400b983ec10b2

**Comment by Viincenttt** [comment]
Live in version 1.3.7
