### ISSUE TITLE
GetInvoiceListAsync : Unprocessable Entity - Non-existent query parameter "include" for this API call

### ISSUE THREAD

**Issue by Pskyco** [Viincenttt/MollieApi#328]
Hi,

While calling ``GetInvoiceListAsync`` from ``InvoicesClient`` with parameter ``incldueLines: true``, here is what I got,

``await _invoicesClient.GetInvoiceListAsync(includeLines: true)``

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Mollie.Api.Client.MollieApiException: Unprocessable Entity - Non-existent query parameter "include" for this API call. Did you mean: "from"?
         at Mollie.Api.Client.BaseMollieClient.ProcessHttpResponseMessage[T](HttpResponseMessage response)
         at Mollie.Api.Client.BaseMollieClient.SendHttpRequest[T](HttpMethod httpMethod, String relativeUri, Object data)
         at Mollie.Api.Client.BaseMollieClient.GetListAsync[T](String relativeUri, String from, Nullable`1 limit, IDictionary`2 otherParameters)
         at Mollie.Api.Client.InvoicesClient.GetInvoiceListAsync(String reference, Nullable`1 year, String from, Nullable`1 limit, Boolean includeLines, Boolean includeSettlements)
```

**Comment by Viincenttt** [comment]
That's weird. The documentation doesn't even state that this method has include parameters, so the error from the Mollie API is correct. The only thing I can do here is remove the `includeLines` and `includeSettlements` parameters from the `GetInvoiceListAsync` method.

**Comment by Pskyco** [comment]
We have the same issue on GetInvoiceAsync. And indeed without those
parameters, we have the lines and settlement détails

Le lun. 25 sept. 2023 à 20:44, Vincent Kok ***@***.***> a
écrit :

**Comment by Viincenttt** [comment]
Thanks for reporting this @Pskyco , I've just merged a pull request to remove those parameters

**Comment by Viincenttt** [comment]
This is now live in 3.4.1.0
