### ISSUE TITLE
System.IO.FileNotFoundException occurred: System.Net.Http

### ISSUE THREAD

**Issue by sprinttovision** [Viincenttt/MollieApi#51]
When I add the Mollie.Api package in a console application and start the PaymentClient this error shows up. What is the problem?

System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Kan bestand of assembly System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Mollie.Api.Client.BaseMollieClient..ctor(String apiKey) in C:\Users\pasca\Documents\Projecten\SBR\Mollie.Api\Client\BaseMollieClient.cs:line 29
   at Mollie.Api.Client.PaymentClient..ctor(String apiKey) in C:\Users\pasca\Documents\Projecten\SBR\Mollie.Api\Client\PaymentClient.cs:line 9
   at SBRMollieKoppeling.Program.Main(String[] args) in C:\Users\pasca\Documents\Projecten\SBR\SBRMollieKoppeling\Program.cs:line 22

Inner Exception 1:
FileNotFoundException: Kan bestand of assembly System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. Het systeem kan het opgegeven bestand niet vinden.

**Comment by lgoudriaan** [comment]
See: #47
